"""Reverse only reviewed Step 16C hunks, retaining all historical byte gates.

The frozen manifest is an explicit acceptance record, never generated by tests.
Any mutation within a hunk stops it matching; any mutation outside remains.
"""
import json
from pathlib import Path

CHANGES = json.loads(Path(__file__).with_name('step16c_historical_changes.json').read_text())

def project(path, text):
    for hunk in CHANGES.get(path, []):
        if hunk['after'] in text:
            assert text.count(hunk['after']) == 1, (path, 'ambiguous Step 16C hunk')
            text = text.replace(hunk['after'], hunk['before'], 1)
    return text
