-- Step 10C-A fixed map resource: rlyeh
-- Pinned donor: neutrality.des at commit 17bc64f77ac566e7b90c0c6c6652e2a5f3a995c0
-- Static body port only; topology, scheduler, and generator hooks remain deferred.
des.level_flags("hardfloor","noteleport","nommap")
des.map({halign="center",valign="center",map=[=[
0                .........         }}...          -----  }}}}}}}}}---------}}
1  .......     ...............    ...}}}..        |...|...}}}}}}..|.......|.}
2 ....}}...H##H................   ...}}.  .       |...+...}}}}}...+.......+.}
3  .......     ...........   ...         .        |...|..}}}}}}}..|.......|.}
4                .......      ...  ----- .  ----- -----}}}}}}}}}..---------}}
5     ........   ++            ..  |...|-S--|...|    |}}}}}}}}}}..}}}}}}}}}}}
6    ... .. .......     ...... ..  |...|....|...|    |}}}}}}..............}}}
7   ..................      -S-++--|...|....|...|    |}}}}...........--------
8 }}... .}}. ... ... ....   |......|-+----+---+------|}}}............|}}....|
9 }.....}}}}............... |.}}}}.+.................|}..............+......|
0 }.....}}}}............... |.}}}}.+.................|}..............+......|
1 }}... .}}. ... ... ....   |......|S--+----+--+-----|}}}............|}}....|
2   ..................      -S-++---.|...|....|..|   |}}}}...........--------
3    ... .. .......     ...... ..   .|...|....|..|   |}}}}}}..............}}}
4     ........   ++            ..   .|...|----|..|   |}}}}}}}}}}..}}}}}}}}}}}
5                .......      ...   .-----    ---------}}}}}}}}}..---------}}
6  .......     ...........   ...    .      ...    |...|..}}}}}}}..|.......|.}
7 ....}}...H##H................      ...  ..}..   |...+...}}}}}...+.......+.}
8  .......     ...............          .. ...    |...|...}}}}}}..|.......|.}
9                .........                        -----  }}}}}}}}}---------}}
0                                                       }}}}}}}}           }}
]=]})
local place={{4,9},{4,10},{3,2},{3,17},{34,2},{44,17},{16,2},{16,17}}
shuffle(place)
des.non_diggable(selection.area(0,0,75,20))
des.non_passwall(selection.area(48,0,49,20))
des.region({region={0,0,52,19},lit=0,type="ordinary"})
des.region({region={53,0,75,19},lit=1,type="ordinary"})
des.region({region={66,1,72,3},lit=0,type="ordinary"})
des.region({region={69,8,74,11},lit=0,type="ordinary"})
des.region({region={66,16,72,18},lit=0,type="ordinary"})
des.altar({coord={4,9},align="noalign",type="altar"})
des.altar({coord={4,10},align="noalign",type="altar"})
des.region({region={1,5,23,14},lit=0,type="temple",filled=1})
des.altar({coord={3,2},align="noalign",type="altar"})
des.region({region={1,1,9,3},lit=0,type="temple",filled=1})
des.altar({coord={16,2},align="noalign",type="altar"})
des.region({region={14,0,26,4},lit=0,type="temple",filled=1})
des.altar({coord={3,17},align="noalign",type="altar"})
des.region({region={1,16,9,18},lit=0,type="temple",filled=1})
des.altar({coord={16,17},align="noalign",type="altar"})
des.region({region={14,15,26,19},lit=0,type="temple",filled=1})
des.altar({coord={36,1},align="noalign",type="altar"})
des.region({region={33,0,39,2},lit=0,type="temple",filled=1})
des.altar({coord={44,17},align="noalign",type="altar"})
des.region({region={40,16,45,18},lit=0,type="temple",filled=1})
des.stair({dir="up",coord={73,9}})
des.teleport_region({region={69,8,74,11},exclude={0,0,0,0},dir="down"})
des.drawbridge({coord={53,9},dir="west",state="closed"})
des.drawbridge({coord={53,10},dir="west",state="closed"})
des.door({state="closed",coord={68,9}})
des.door({state="closed",coord={68,10}})
des.door({state="locked",coord={65,2}})
des.door({state="locked",coord={73,2}})
des.door({state="locked",coord={65,17}})
des.door({state="locked",coord={73,17}})
des.door({state="closed",coord={53,2}})
des.door({state="closed",coord={53,17}})
des.door({state="closed",coord={36,8}})
des.door({state="closed",coord={41,8}})
des.door({state="closed",coord={45,8}})
des.door({state="closed",coord={38,11}})
des.door({state="closed",coord={43,11}})
des.door({state="closed",coord={46,11}})
des.door({state="locked",coord={35,11}})
des.door({state="locked",coord={40,5}})
des.door({state="locked",coord={34,9}})
des.door({state="locked",coord={34,10}})
des.door({state="locked",coord={16,5}})
des.door({state="locked",coord={17,5}})
des.door({state="locked",coord={16,14}})
des.door({state="locked",coord={17,14}})
des.door({state="locked",coord={30,7}})
des.door({state="locked",coord={31,7}})
des.door({state="locked",coord={30,12}})
des.door({state="locked",coord={31,12}})
des.door({state="locked",coord={28,7}})
des.door({state="locked",coord={28,12}})
des.monster({class=";",coord={59,1},asleep=true,peaceful=false})
des.monster({class="h",id="deep one",coord={57,4},asleep=true,peaceful=false})
des.monster({class=";",coord={54,7},asleep=true,peaceful=false})
des.monster({class="h",id="deep one",coord={54,13},asleep=true,peaceful=false})
des.monster({class=";",coord={58,15},asleep=true,peaceful=false})
des.monster({class="h",id="deep one",coord={60,18},asleep=true,peaceful=false})
des.monster({class=";",coord={70,5},asleep=true,peaceful=false})
des.monster({class="h",id="deep one",coord={72,14},asleep=true,peaceful=false})
des.monster({class="h",id="star spawn",coord={52,2},asleep=true,peaceful=false})
des.object({class="/",id="lightning",coord={52,2}})
des.object({class="(",id="chest",coord={51,2}})
des.monster({class="g",id="nightgaunt",coord={56,1},asleep=true,peaceful=false})
des.monster({class="g",id="nightgaunt",coord={55,2},asleep=true,peaceful=false})
des.monster({class="h",id="star spawn",coord={52,17},asleep=true,peaceful=false})
des.object({class="/",id="lightning",coord={52,17}})
des.object({class="(",id="chest",coord={51,17}})
des.monster({class="g",id="nightgaunt",coord={56,18},asleep=true,peaceful=false})
des.monster({class="g",id="nightgaunt",coord={55,17},asleep=true,peaceful=false})
des.monster({class="H",id="Father Dagon",coord={56,8},asleep=true,peaceful=false})
des.monster({class="h",id="deeper one",coord={61,6},asleep=true,peaceful=false})
des.monster({class="h",id="deeper one",coord={64,7},asleep=true,peaceful=false})
des.monster({class="H",id="Mother Hydra",coord={56,11},asleep=true,peaceful=false})
des.monster({class="h",id="deeper one",coord={61,13},asleep=true,peaceful=false})
des.monster({class="h",id="deeper one",coord={64,12},asleep=true,peaceful=false})
des.monster({class="h",id="deep one",coord={67,1},asleep=true,peaceful=false})
des.object({class="(",id="chest",coord={68,1}})
des.monster({class="h",id="deep one",coord={69,1},asleep=true,peaceful=false})
des.object({class="(",id="chest",coord={70,1}})
des.monster({class="h",id="deep one",coord={71,1},asleep=true,peaceful=false})
des.monster({class="h",id="deep one",coord={67,3},asleep=true,peaceful=false})
des.object({class="(",id="chest",coord={68,3}})
des.monster({class="h",id="deep one",coord={69,3},asleep=true,peaceful=false})
des.object({class="(",id="chest",coord={70,3}})
des.monster({class="h",id="deep one",coord={71,3},asleep=true,peaceful=false})
des.monster({class="h",id="deep one",coord={67,16},asleep=true,peaceful=false})
des.object({class="(",id="chest",coord={68,16}})
des.monster({class="h",id="deep one",coord={69,16},asleep=true,peaceful=false})
des.object({class="(",id="chest",coord={70,16}})
des.monster({class="h",id="deep one",coord={71,16},asleep=true,peaceful=false})
des.monster({class="h",id="deep one",coord={67,18},asleep=true,peaceful=false})
des.object({class="(",id="chest",coord={68,18}})
des.monster({class="h",id="deep one",coord={69,18},asleep=true,peaceful=false})
des.object({class="(",id="chest",coord={70,18}})
des.monster({class="h",id="deep one",coord={71,18},asleep=true,peaceful=false})
des.trap({type="board",coord={65,8}})
des.trap({type="board",coord={65,11}})
des.trap({type="board",coord={61,8}})
des.trap({type="board",coord={61,11}})
des.trap({type="board",coord={58,8}})
des.trap({type="board",coord={58,11}})
des.trap({type="board",coord={63,2}})
des.trap({type="board",coord={63,17}})
des.trap({type="board",coord={55,2}})
des.trap({type="board",coord={55,17}})
des.trap({type="board"})
des.trap({type="board"})
des.trap({type="board"})
des.trap({type="board"})
des.trap({type="board"})
des.trap({type="board"})
des.trap({type="board"})
des.trap({type="board"})
des.trap({type="board"})
des.trap({type="board"})
des.trap({type="board"})
des.trap({type="board"})
des.trap({type="board"})
des.trap({type="board"})
des.monster({class="h",id="master mind flayer",coord={47,9},asleep=true,peaceful=false})
des.object({class="/",id="slow monster",coord={47,9}})
des.object({class="/",id="fire",coord={47,9},buc="blessed",spe=3})
des.monster({class="h",id="master mind flayer",coord={49,10},asleep=true,peaceful=false})
des.object({class="/",id="speed monster",coord={49,10}})
des.object({class="/",id="cold",coord={49,10},buc="blessed",spe=3})
des.monster({class="h",id="mind flayer",coord={35,6},asleep=true,peaceful=false})
if percent(10) then
des.object({class="!",id="space mead",coord={35,5},buc="blessed",spe=0})
end
des.monster({class="h",id="mind flayer",coord={37,6},asleep=true,peaceful=false})
if percent(10) then
des.object({class="!",id="space mead",coord={37,5},buc="blessed",spe=0})
end
des.monster({class="h",id="star spawn",coord={39,6},asleep=true,peaceful=false})
if percent(10) then
des.object({class="!",id="space mead",coord={39,6},buc="blessed",spe=0})
end
des.monster({class="h",id="mind flayer",coord={42,6},asleep=true,peaceful=false})
if percent(10) then
des.object({class="!",id="space mead",coord={42,6},buc="blessed",spe=0})
end
des.monster({class="h",id="mind flayer",coord={44,5},asleep=true,peaceful=false})
if percent(10) then
des.object({class="!",id="space mead",coord={44,5},buc="blessed",spe=0})
end
des.monster({class="h",id="mind flayer",coord={46,5},asleep=true,peaceful=false})
if percent(10) then
des.object({class="!",id="space mead",coord={46,5},buc="blessed",spe=0})
end
des.monster({class="h",id="mind flayer",coord={37,13},asleep=true,peaceful=false})
if percent(10) then
des.object({class="!",id="space mead",coord={37,14},buc="blessed",spe=0})
end
des.monster({class="h",id="mind flayer",coord={39,12},asleep=true,peaceful=false})
if percent(10) then
des.object({class="!",id="space mead",coord={39,14},buc="blessed",spe=0})
end
des.monster({class="h",id="mind flayer",coord={41,12},asleep=true,peaceful=false})
if percent(10) then
des.object({class="!",id="space mead",coord={41,13},buc="blessed",spe=0})
end
des.monster({class="h",id="mind flayer",coord={44,13},asleep=true,peaceful=false})
if percent(10) then
des.object({class="!",id="space mead",coord={44,13},buc="blessed",spe=0})
end
des.monster({class="h",id="mind flayer",coord={46,12},asleep=true,peaceful=false})
if percent(10) then
des.object({class="!",id="space mead",coord={46,14},buc="blessed",spe=0})
end
des.monster({class="h",id="mind flayer",coord={47,13},asleep=true,peaceful=false})
if percent(10) then
des.object({class="!",id="space mead",coord={47,14},buc="blessed",spe=0})
end
des.trap({type="board",coord={35,9}})
des.trap({type="board",coord={35,10}})
des.monster({class=";",id="kraken",coord={29,9},asleep=true,peaceful=false})
des.monster({class=";",id="kraken",coord={30,9},asleep=true,peaceful=false})
des.monster({class=";",id="kraken",coord={31,9},asleep=true,peaceful=false})
des.monster({class=";",id="kraken",coord={32,9},asleep=true,peaceful=false})
des.monster({class=";",id="kraken",coord={29,10},asleep=true,peaceful=false})
des.monster({class=";",id="kraken",coord={30,10},asleep=true,peaceful=false})
des.monster({class=";",id="kraken",coord={31,10},asleep=true,peaceful=false})
des.monster({class=";",id="kraken",coord={32,10},asleep=true,peaceful=false})
des.monster({class="&",id="Great Cthulhu",coord=place[1],asleep=true,peaceful=false})
des.monster({class="h",id="star spawn",coord=place[2],peaceful=false})
des.object({class="(",id="universal key",coord=place[3],buc="uncursed",name="0",name="The Silver Key"})
des.monster({class="&",id="priest of an unknown god",coord=place[4],peaceful=false})
des.monster({class="&",id="priest of an unknown god",coord=place[5],peaceful=false})
des.monster({class="h",id="star spawn",coord=place[6],peaceful=false})
des.trap({type="fire",coord={15,6}})
des.trap({type="magic",coord={16,6}})
des.trap({type="fire",coord={17,6}})
des.trap({type="fire",coord={15,13}})
des.trap({type="magic",coord={16,13}})
des.trap({type="fire",coord={17,13}})
des.monster({class=";",id="kraken",coord={9,10},asleep=true,peaceful=false})
des.object({class="(",id="chest",coord={2,9}})
des.object({class="(",id="chest",coord={2,10}})
des.trap({type="fire",coord={25,1}})
des.trap({type="fire",coord={25,2}})
des.trap({type="magic",coord={26,1}})
des.trap({type="magic",coord={26,2}})
des.trap({type="fire",coord={27,1}})
des.trap({type="fire",coord={27,2}})
des.object({class="(",id="chest",coord={14,2}})
des.trap({type="board",coord={9,2}})
des.monster({class=";",id="kraken",coord={5,2},asleep=true,peaceful=false})
des.object({class="(",id="chest",coord={1,2}})
des.trap({type="fire",coord={25,17}})
des.trap({type="fire",coord={25,18}})
des.trap({type="magic",coord={26,17}})
des.trap({type="magic",coord={26,18}})
des.trap({type="fire",coord={27,17}})
des.trap({type="fire",coord={27,18}})
des.object({class="(",id="chest",coord={14,17}})
des.trap({type="board",coord={9,17}})
des.monster({class=";",id="kraken",coord={5,17},asleep=true,peaceful=false})
des.object({class="(",id="chest",coord={1,17}})
des.trap({type="board",coord={39,1}})
des.monster({class=";",id="kraken",coord={36,1},asleep=true,peaceful=false})
des.object({class="(",id="chest",coord={33,1}})
des.trap({type="board",coord={37,17}})
des.monster({class=";",id="kraken",coord={43,17},asleep=true,peaceful=false})
des.object({class="(",id="chest",coord={45,17}})
des.trap({type="teleport",coord={28,6}})
des.monster({class="b",id="shoggoth",coord={27,6},asleep=true,peaceful=false})
des.monster({class="b",id="shoggoth",coord={25,6},asleep=true,peaceful=false})
des.monster({class="b",id="shoggoth",coord={23,6},asleep=true,peaceful=false})
des.trap({type="teleport",coord={28,13}})
des.monster({class="b",id="shoggoth",coord={27,13},asleep=true,peaceful=false})
des.monster({class="b",id="shoggoth",coord={25,13},asleep=true,peaceful=false})
des.monster({class="b",id="shoggoth",coord={23,13},asleep=true,peaceful=false})
des.object({})
des.object({})
des.object({})
des.object({})
des.object({})
des.object({})
des.object({})
des.object({})
des.object({})
des.object({})
des.object({})
des.object({})
