-- NetHack special level; see doc/step9a.md.
-- UnNetHack 439b8d63d3d1ca78fb08588dd43f61874114b21a:dat/sheol.des
des.level_init({style="solidfill", fg=" "})
des.level_flags("hardfloor", "noteleport", "noflip")
des.level_init({style="sheol"})
des.map({x=1,y=0,map="x"}) -- one-cell transparent map resets the full coordinate frame
des.levregion({region={1, 0, 15, 20}, exclude={16, 0, 64, 20}, type="stair-up", region_islev=1, exclude_islev=1})
des.levregion({region={65, 0, 79, 20}, exclude={16, 0, 64, 20}, type="stair-down", region_islev=1, exclude_islev=1})
des.monster({id="crystal ice golem"})
des.monster({id="crystal ice golem"})
des.monster({id="blue slime"})
if percent(50) then des.monster({id="Punisher"}) end
des.monster()
des.monster()
des.monster()
des.monster()
des.monster()
des.monster()
des.monster()
des.monster()
des.monster()
des.object({class="*"})
des.object({class="!"})
des.object({class="\""})
des.object({class="?"})
des.object({class="/"})
des.object({class="="})
des.object({class="+"})
des.object({class="("})
des.object({class=")"})
if percent(33) then des.object({class="/",id="fire"}) end
des.trap()
des.trap()
des.trap()
des.trap()
