/* Shared persistent ordinary-affix definitions. */
#ifndef AFFIX_H
#define AFFIX_H
/* Physical bound and current canonical maximum, maintained in one place. */
#define ENHANCEMENT_MAX_SLOTS 2
struct affix_slot {
    uint8 property; /* canonical EP_*; zero means Open */
    uint8 tier;     /* zero means unused capacity, otherwise immutable 1..4 */
    uint8 history;  /* saturates at 10 */
};
enum equipment_property {
    EP_NONE, EP_FIRE, EP_COLD, EP_SHOCK, EP_TRUEFLIGHT,
    EP_FIRE_II, EP_COLD_II, EP_SHOCK_II,
    EP_FIRE_III, EP_COLD_III, EP_SHOCK_III, EP_PRIMORDIAL,
    EP_SEARCHING, EP_WARNING, EP_STEALTH,
    EP_FIRE_RES, EP_COLD_RES, EP_SHOCK_RES, EP_POISON_RES,
    EP_SPEED, EP_REGEN, EP_DISPLACED, EP_SLOW_DIGEST, EP_MAGIC_RES, EP_REFLECTION,
    EP_STR_I, EP_STR_II, EP_STR_III, EP_STR_IV,
    EP_DEX_I, EP_DEX_II, EP_DEX_III, EP_DEX_IV,
    EP_HP_I, EP_HP_III, EP_HP_IV, EP_PROT_I, EP_PROT_III, EP_PROT_IV,
    EP_CON_I, EP_CON_II, EP_CON_III, EP_CON_IV,
    EP_MANA_I, EP_MANA_II, EP_MANA_III, EP_MANA_IV,
    EP_INT_I, EP_INT_II, EP_INT_III, EP_INT_IV,
    EP_WIS_I, EP_WIS_II, EP_WIS_III, EP_WIS_IV,
    EP_CHA_I, EP_CHA_II, EP_CHA_III, EP_CHA_IV,
    EP_SLEEP_RES, EP_SEE_INVIS, EP_JUMPING, EP_BREATHING, EP_TELEPATHY,
    EP_TELEPORT_CONTROL, EP_POLYMORPH_CONTROL, EP_FLYING,
    EP_VAMPIRIC_I, EP_VAMPIRIC_II, EP_VAMPIRIC_III, EP_VAMPIRIC_IV, EP_ACID_I, EP_ACID_II, EP_ACID_III, EP_ANARCHIC_I, EP_ANARCHIC_II, EP_AXIOMATIC_I, EP_AXIOMATIC_II, EP_STONING_I, EP_STONING_II, EP_STONING_III, EP_STONING_IV, EP_WARDING, EP_CASTING_II, EP_CASTING_IV, EP_LIGHTNESS_I, EP_LIGHTNESS_II, EP_LIGHTNESS_III, EP_THORNS_I, EP_THORNS_II, EP_DR_I, EP_DR_II, EP_DR_III, EP_DR_IV,
    EP_EROSION_I, EP_EROSION_II, EP_EROSION_III, EP_EROSION_IV, EP_CURSE_II, EP_CURSE_IV, EP_DISCERNMENT, EP_PURIFICATION_I, EP_PURIFICATION_II, EP_PURIFICATION_III, EP_PURIFICATION_IV, EP_EXCAVATING, EP_COMMERCE_I, EP_COMMERCE_III, EP_TREASURE_I, EP_TREASURE_II, EP_ARCANE_II, EP_ARCANE_III, EP_ARMOR_STORAGE_II, EP_ARMOR_STORAGE_III, EP_WEAPON_STORAGE_II, EP_WEAPON_STORAGE_III, EP_WATERTIGHT, EP_COUNT
};
#endif
